### ISSUE TITLE
Attribute values cleanup

### ISSUE THREAD

**Issue by acrividenco** [inveniosoftware/invenio-saml#38]
Package version (if known): latest

## Describe the bug
Federated accounts almost always have usernames in the form firstname.lastname . Invenio does not support "." in usernames and parsing assertion values from config is not possible, resulting in registration errors. Please add some values cleanup in `account_info`

**Comment by egabancho** [comment]
Hi @acrividenco, thanks for the report.
It isn't easy to cover all cases and combinations to clean up user names. We added the possibility to use a custom account info extraction function. You can check this test for an example: https://github.com/inveniosoftware/invenio-saml/blob/master/tests/test_handlers.py#L170.
Hopefully this helps.
