### ISSUE TITLE
Find a way to build the docs

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio-saml#5]
Read-the-docs is missing the XML system libraries and the build fails. We can either try to make a PR to read-the-docs to add this library to the base configuration used or push the docs to github pages.

(Extracted from #3)

**Comment by egabancho** [comment]
@ntarocco I don't have access to read the docs. Can you check if the docs are being built now?

**Comment by ntarocco** [comment]
> @ntarocco I don't have access to read the docs. Can you check if the docs are being built now?

Just got access, it looks like that it is failing. You should be able to access [this](https://beta.readthedocs.org/api/v2/build/24024459.txt).
